---
name: isotovideo - github action
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "registry.opensuse.org/devel/openqa/containers/isotovideo:qemu-x86"
    steps:
      - uses: actions/checkout@v2
      - name: install jq
        run: zypper -n in jq

      - name: Run isotovideo against test code
        run: isotovideo qemu_no_kvm=1 casedir=.

      - name: fail if any test module failed
        run: jq .result testresults/result-*.json | grep -v ok && echo "Test modules failed" && exit 1


      - name: Collect failure logs
        if: ${{ failure() }}
        run: ls -lai testresults && find testresults -type f

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Collect failure logs
          path: testresults